---
title: "STAT 443 Statistics Project"
author: "Group 5 (and names here)"
date: "2022-02-22" #change to due date
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load libraries
require(data.table)
library(tidyverse)
library(ggplot2)
library(GGally)
```


```{r load data}
project_data = fread("Group5Data.csv")
project_data = project_data[,-"CO"]
project_data = as.data.frame(project_data)
names(project_data) <- c("Ambient Temperature", "Ambient Pressure", "Ambient Humidity", "Air Filter Difference Pressure", "Gas Turbine Exhaust Pressure", "Turbine Inlet temperature", "Turbine After Temperature", "Compressor Discharge Pressure", "Turbine Energy Yield", "Nitrogen Oxides")
head(project_data)
```



```{r fig.width= 10, fig.height= 10}
#ggpairs(project_data )
#pairs(project_data, col = "blue", alpha = 0.7)
#discuss correlation, etc. 
```

<<<<<<< HEAD
```{r}
pairs(project_data)
```


```{r}
fullmodel <- lm(project_data$`Nitrogen Oxides` ~., data = project_data)
stepmodel <- step(fullmodel, direction = "both")
stepmodel
```

=======
```{r fig.width = 5, fig.height= 5}
#library(caret)
library(EnvStats)
#process <- preProcess(as.data.frame(project_data[,'Turbine After Temperature']), method=c("range"))
project_data[,'Turbine After Temperature'] = log(project_data[,'Turbine After Temperature'])

ggplot(gather(project_data), aes(value)) + geom_histogram(bins = 20) + facet_wrap(~key, scales = 'free_x')


```
Possibly binning turbine after temperatures, check turbine inlet temperature, 

#Todo: 
>>>>>>> c25517dc708b1b300cda09d9d7ca3915e892b4d6
